name: Deploy to staging

on:
  push:
    branches:
      - develop
  repository_dispatch:
    types: rebuild-staging
  #schedule:
  #  - cron: '10 0 * * *'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Set the REPOSITORY_URL_SITE environment variable
      run: echo "REPOSITORY_URL_SITE=https://github.com/$GITHUB_REPOSITORY" >> $GITHUB_ENV
    - name: Build the site
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
        bundle exec jekyll build --baseurl=/${{ env.GITHUB_REPOSITORY_NAME_PART }}
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
